/***********************************************************************

doom_player.script

This script contains any player specific code.

***********************************************************************/

object player : player_base {
	weapon_base weapon;
	boolean		weapon_changed;
	boolean		start_fire;

	void		init();
};

/*
=====================
player::init
=====================
*/
void player::init() {
	weapon_changed = false;
	start_fire = false;
}
